on: push

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./
        with:
          myInput: 'Chad Crowell'
      - name: output
        run: |
          echo ${{ steps.hello.ouputs }}
          echo "total memory successfully output"
